# Generated by Django 4.1.4 on 2022-12-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HslSertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='zips/')),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
    ]
