# Generated by Django 4.1.4 on 2022-12-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sertifikat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hslsertifikat',
            name='caption',
        ),
    ]
