# Generated by Django 4.1.4 on 2022-12-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usersnormal',
        ),
    ]
